/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jshop.views.views;

import javax.swing.JButton;

/**
 *
 * @author juan-campos
 */
public class VMenu extends javax.swing.JPanel {

    /**
     * Creates new form VMenu
     */
    public VMenu() {
        initComponents();
    }

    public void showView(JButton o) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product_items = new javax.swing.JPanel();
        brand_button = new javax.swing.JButton();
        supplier_button = new javax.swing.JButton();
        distribution_button = new javax.swing.JButton();
        category_button = new javax.swing.JButton();
        employeers_items = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tools_items = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(450, 300));
        setPreferredSize(new java.awt.Dimension(950, 600));
        setLayout(new java.awt.GridLayout(1, 3));

        product_items.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));
        product_items.setLayout(new java.awt.GridLayout(6, 1));

        brand_button.setText("Marcas");
        product_items.add(brand_button);

        supplier_button.setText("Proveedores");
        product_items.add(supplier_button);

        distribution_button.setText("Distribuidores");
        product_items.add(distribution_button);

        category_button.setText("Categoria");
        product_items.add(category_button);

        add(product_items);

        employeers_items.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));
        employeers_items.setLayout(new java.awt.GridLayout(6, 1));

        jButton1.setText("Empleados");
        employeers_items.add(jButton1);

        jButton6.setText("Administrador");
        employeers_items.add(jButton6);

        add(employeers_items);

        tools_items.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas"));
        tools_items.setLayout(new java.awt.GridLayout(6, 1));

        jButton8.setText("Ayuda");
        tools_items.add(jButton8);

        jButton9.setText("jButton9");
        tools_items.add(jButton9);

        jButton5.setText("jButton5");
        tools_items.add(jButton5);

        add(tools_items);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brand_button;
    private javax.swing.JButton category_button;
    private javax.swing.JButton distribution_button;
    private javax.swing.JPanel employeers_items;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel product_items;
    private javax.swing.JButton supplier_button;
    private javax.swing.JPanel tools_items;
    // End of variables declaration//GEN-END:variables
}
