/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jshop.views.views;

/**
 *
 * @author juan-campos
 */
public class VProducts extends javax.swing.JPanel {

    /**
     * Creates new form VProducts
     */
    public VProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        save_panel = new javax.swing.JPanel();
        pc_name = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pc_marker = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        options_panel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        search_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(950, 600));
        setName("Products"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        save_panel.setLayout(new java.awt.GridLayout(12, 0));

        pc_name.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nombre");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));
        pc_name.add(jLabel1, java.awt.BorderLayout.LINE_START);
        pc_name.add(jTextField1, java.awt.BorderLayout.CENTER);

        jLabel10.setPreferredSize(new java.awt.Dimension(150, 20));
        pc_name.add(jLabel10, java.awt.BorderLayout.LINE_END);

        save_panel.add(pc_name);

        pc_marker.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Marca");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 16));
        pc_marker.add(jLabel2, java.awt.BorderLayout.LINE_START);
        pc_marker.add(jTextField2, java.awt.BorderLayout.CENTER);

        jCheckBox1.setText("M");
        jCheckBox1.setPreferredSize(new java.awt.Dimension(150, 20));
        pc_marker.add(jCheckBox1, java.awt.BorderLayout.LINE_END);

        save_panel.add(pc_marker);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Contenido");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel6.add(jLabel3, java.awt.BorderLayout.LINE_START);
        jPanel6.add(jTextField3, java.awt.BorderLayout.CENTER);

        jCheckBox2.setText("M");
        jCheckBox2.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel6.add(jCheckBox2, java.awt.BorderLayout.LINE_END);

        save_panel.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("UDM");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel7.add(jLabel4, java.awt.BorderLayout.LINE_START);

        jCheckBox3.setText("M");
        jCheckBox3.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel7.add(jCheckBox3, java.awt.BorderLayout.LINE_END);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(jComboBox4, java.awt.BorderLayout.CENTER);

        save_panel.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Marca");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel8.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jCheckBox4.setText("M");
        jCheckBox4.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel8.add(jCheckBox4, java.awt.BorderLayout.LINE_END);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(jComboBox3, java.awt.BorderLayout.CENTER);

        save_panel.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Distribuidor");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel9.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jCheckBox5.setText("M");
        jCheckBox5.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel9.add(jCheckBox5, java.awt.BorderLayout.LINE_END);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox2, java.awt.BorderLayout.CENTER);

        save_panel.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Categoria");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel10.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jCheckBox7.setText("M");
        jCheckBox7.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel10.add(jCheckBox7, java.awt.BorderLayout.LINE_END);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(jComboBox1, java.awt.BorderLayout.CENTER);

        save_panel.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Multimedia");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel11.add(jLabel8, java.awt.BorderLayout.LINE_START);

        jCheckBox6.setText("M");
        jCheckBox6.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel11.add(jCheckBox6, java.awt.BorderLayout.LINE_END);

        jButton3.setText("jButton3");
        jPanel11.add(jButton3, java.awt.BorderLayout.CENTER);

        save_panel.add(jPanel11);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("F. de Registro");
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel12.add(jLabel9, java.awt.BorderLayout.LINE_START);
        jPanel12.add(jTextField9, java.awt.BorderLayout.CENTER);

        jLabel11.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel12.add(jLabel11, java.awt.BorderLayout.LINE_END);

        save_panel.add(jPanel12);
        save_panel.add(jLabel14);

        options_panel.setLayout(new java.awt.GridLayout(1, 4, 5, 5));
        options_panel.add(jLabel17);

        jButton1.setText("Guardar");
        options_panel.add(jButton1);

        jButton6.setText("Cancelar");
        options_panel.add(jButton6);

        jButton2.setText("Eliminar");
        options_panel.add(jButton2);
        options_panel.add(jLabel18);

        save_panel.add(options_panel);

        jTabbedPane1.addTab("Registro de productos", save_panel);

        search_panel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        search_panel.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        search_panel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Consulta de productos", search_panel);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel options_panel;
    private javax.swing.JPanel pc_marker;
    private javax.swing.JPanel pc_name;
    private javax.swing.JPanel save_panel;
    private javax.swing.JPanel search_panel;
    // End of variables declaration//GEN-END:variables
}
