/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jshop.views.views;

import com.jutil.framework.WindowStates;
import java.time.LocalDate;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author juan-campos
 */
public class VEmployees extends JPanel implements WindowStates {

    /**
     * Creates new form VEmployees
     */
    public VEmployees() {
        initComponents();
        build();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        field_name = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        field_last_name1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        field_last_name2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        field_day = new javax.swing.JComboBox<>();
        field_month = new javax.swing.JComboBox<>();
        field_year = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        field_address = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        field_number_phone = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        field_email = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        field_user = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        field_password = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        field_position = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        field_state = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(950, 600));
        setName("Employees"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel19.setPreferredSize(new java.awt.Dimension(950, 40));
        jPanel19.setLayout(new java.awt.GridLayout());

        jButton2.setText("Cancelar");
        jPanel19.add(jButton2);

        jButton1.setText("Guardar");
        jPanel19.add(jButton1);

        jPanel1.add(jPanel19, java.awt.BorderLayout.SOUTH);

        jPanel18.setLayout(new java.awt.GridLayout(1, 3));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Perosnal"));
        jPanel3.setLayout(new java.awt.GridLayout(8, 1));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Nombre");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel7.add(jLabel3, java.awt.BorderLayout.NORTH);
        jPanel7.add(field_name, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Apellido Paterno");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel6.add(jLabel2, java.awt.BorderLayout.NORTH);
        jPanel6.add(field_last_name1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Apellido Materno");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel8.add(jLabel1, java.awt.BorderLayout.NORTH);
        jPanel8.add(field_last_name2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Cumpleaños");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel9.add(jLabel4, java.awt.BorderLayout.NORTH);

        jPanel10.setLayout(new java.awt.GridLayout(1, 3));

        jPanel10.add(field_day);

        jPanel10.add(field_month);

        field_year.setModel(new javax.swing.SpinnerNumberModel(2000, 1930, null, 1));
        jPanel10.add(field_year);

        jPanel9.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9);

        jPanel18.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de contacto"));
        jPanel4.setLayout(new java.awt.GridLayout(8, 1));

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Direccion.");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel11.add(jLabel5, java.awt.BorderLayout.NORTH);
        jPanel11.add(field_address, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Numero Telefonico.");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel12.add(jLabel6, java.awt.BorderLayout.NORTH);
        jPanel12.add(field_number_phone, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel12);

        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("Correo Electronico.");
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel16.add(jLabel10, java.awt.BorderLayout.NORTH);
        jPanel16.add(field_email, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel16);

        jPanel18.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de usuario"));
        jPanel5.setLayout(new java.awt.GridLayout(8, 1));

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Usuario");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel13.add(jLabel7, java.awt.BorderLayout.NORTH);
        jPanel13.add(field_user, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Contraseña");
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel14.add(jLabel8, java.awt.BorderLayout.NORTH);
        jPanel14.add(field_password, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel14);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("Cargo");
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel15.add(jLabel9, java.awt.BorderLayout.NORTH);

        field_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel15.add(field_position, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel15);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel11.setText("Estado.");
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel17.add(jLabel11, java.awt.BorderLayout.NORTH);

        field_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel17.add(field_state, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel17);

        jPanel18.add(jPanel5);

        jPanel1.add(jPanel18, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Registro de personal", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel20, java.awt.BorderLayout.NORTH);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Consultar Personal", jPanel2);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_address;
    private javax.swing.JComboBox<Integer> field_day;
    private javax.swing.JTextField field_email;
    private javax.swing.JTextField field_last_name1;
    private javax.swing.JTextField field_last_name2;
    private javax.swing.JComboBox<Integer> field_month;
    private javax.swing.JTextField field_name;
    private javax.swing.JTextField field_number_phone;
    private javax.swing.JTextField field_password;
    private javax.swing.JComboBox<String> field_position;
    private javax.swing.JComboBox<String> field_state;
    private javax.swing.JTextField field_user;
    private javax.swing.JSpinner field_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void build() {
        components();
        finalState();
        initialState();
        events();

    }

    @Override
    public void events() {
    }

    @Override
    public void components() {
    }

    @Override
    public void initialState() {
    }

    @Override
    public void finalState() {
        LocalDate ld = LocalDate.now();
        dayFill(field_day, 1, ld.getMonth().length(ld.isLeapYear()));
        dayFill(field_month, 1, 12);
        SpinnerNumberModel sp_model = (SpinnerNumberModel) field_year.getModel();
        sp_model.setMinimum(LocalDate.MIN.getYear());
        sp_model.setMaximum(ld.getYear());
    }

    private void dayFill(JComboBox<Integer> comboBox, int start, int end) {
        for (int i = start; i <= end; i++) {
            comboBox.addItem(i);
        }
    }

}
