/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jshop.views.windows;

import com.jshop.views.views.VEmployees;
import com.jshop.views.views.VHome;
import com.jshop.views.views.VProducts;
import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author juan-campos
 */
public class WMain extends javax.swing.JFrame {

    private JButton[] buttons_option;
    private JPanel[] views;

    /**
     * Creates new form WMain
     *
     * @param login
     */
    public WMain(WLogin login) {
        initComponents();
        this.login = login;
        ly = (CardLayout) center_panel.getLayout();
        home_panel = new VHome();
        products_panel = new VProducts();
        employees_panel = new VEmployees();
        views = new JPanel[]{
            home_panel, employees_panel, products_panel
        };
        //
        center_panel.add(home_panel.getName(), home_panel);
        center_panel.add(products_panel.getName(), products_panel);
        center_panel.add(employees_panel.getName(), employees_panel);
        //
        ly.show(center_panel, home_panel.getName());

        buttons_option = new JButton[]{
            btn_home, btn_inventory, btn_products, btn_exit
        };

        for (JButton i : buttons_option) {
            i.addActionListener(e -> showView((JButton) e.getSource()));

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        west_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_products = new javax.swing.JButton();
        btn_inventory = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        center_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));

        west_panel.setPreferredSize(new java.awt.Dimension(300, 600));
        west_panel.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setToolTipText("buscar");
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(jButton1, java.awt.BorderLayout.LINE_START);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inicio");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jButton2.setToolTipText("Menu");
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(jButton2, java.awt.BorderLayout.LINE_END);

        west_panel.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Foto");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(6, 0));

        btn_home.setText("Inicio");
        jPanel3.add(btn_home);

        btn_products.setText("Productos");
        jPanel3.add(btn_products);

        btn_inventory.setText("Inventario");
        jPanel3.add(btn_inventory);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        west_panel.add(jPanel1, java.awt.BorderLayout.CENTER);

        btn_exit.setText("Salir");
        btn_exit.setMinimumSize(new java.awt.Dimension(100, 50));
        btn_exit.setPreferredSize(new java.awt.Dimension(100, 50));
        west_panel.add(btn_exit, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(west_panel, java.awt.BorderLayout.LINE_START);

        center_panel.setLayout(new java.awt.CardLayout());
        getContentPane().add(center_panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showView(JButton o) {
        if (btn_products == o) {
            ly.show(center_panel, products_panel.getName());
        } else if (btn_inventory == o) {

        } else if (btn_home == o) {
            ly.show(center_panel, home_panel.getName());
        } else {
            setVisible(false);
            dispose();
            login.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_inventory;
    private javax.swing.JButton btn_products;
    private javax.swing.JPanel center_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel west_panel;
    // End of variables declaration//GEN-END:variables
    private final CardLayout ly;
    private final VHome home_panel;
    private final VProducts products_panel;
    private final VEmployees employees_panel;
    //
    private final WLogin login;
}
